// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountEntityStates(ctx context.Context, adapter string) (int64, error)
	DeleteOldEntityStates(ctx context.Context, arg DeleteOldEntityStatesParams) error
	GetEntityStatesByEntity(ctx context.Context, entityID string) ([]EntityState, error)
	GetEntityStatesByScope(ctx context.Context, scopeID string) ([]EntityState, error)
	GetEntityStatesByScopeSince(ctx context.Context, arg GetEntityStatesByScopeSinceParams) ([]EntityState, error)
	GetSignalByID(ctx context.Context, id string) (Signal, error)
	GetSignalEvidence(ctx context.Context, signalID string) ([]SignalEvidence, error)
	InsertEntityState(ctx context.Context, arg InsertEntityStateParams) error
	InsertSignal(ctx context.Context, arg InsertSignalParams) error
	InsertSignalEvidence(ctx context.Context, arg InsertSignalEvidenceParams) error
}

var _ Querier = (*Queries)(nil)
