// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/proto/chronos/v1/chronos.proto

package chronosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChronosService_Ingest_FullMethodName           = "/chronos.v1.ChronosService/Ingest"
	ChronosService_IngestBatch_FullMethodName      = "/chronos.v1.ChronosService/IngestBatch"
	ChronosService_ListSignals_FullMethodName      = "/chronos.v1.ChronosService/ListSignals"
	ChronosService_GetSignal_FullMethodName        = "/chronos.v1.ChronosService/GetSignal"
	ChronosService_StreamSignals_FullMethodName    = "/chronos.v1.ChronosService/StreamSignals"
	ChronosService_ValidateConfig_FullMethodName   = "/chronos.v1.ChronosService/ValidateConfig"
	ChronosService_ExportFederation_FullMethodName = "/chronos.v1.ChronosService/ExportFederation"
)

// ChronosServiceClient is the client API for ChronosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChronosService is the gRPC transport for the Chronos perception engine.
// It mirrors the HTTP REST surface: ingest observations and query signals.
// The service is signals-only: no Title, Summary, Suggestion, or dismissal.
type ChronosServiceClient interface {
	// Ingest persists a single EntityState observation. Detection is not
	// triggered automatically; the scheduler or compute pipeline handles
	// detection separately. Unary — batch ingest is IngestBatch.
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	// IngestBatch persists many observations in one RPC. Validation is
	// all-or-nothing, matching POST /v1/ingest/batch.
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error)
	// ListSignals returns signals matching the provided filter.
	ListSignals(ctx context.Context, in *ListSignalsRequest, opts ...grpc.CallOption) (*ListSignalsResponse, error)
	// GetSignal returns a single signal by ID.
	GetSignal(ctx context.Context, in *GetSignalRequest, opts ...grpc.CallOption) (*Signal, error)
	// StreamSignals is the gRPC equivalent of GET /v1/signals/stream.
	// Requires the in-process detection scheduler. Returns Unimplemented
	// when streaming is not attached. Each frame is a StreamSignalsResponse
	// so the stream type is unique from GetSignal's Signal return
	// (RPC_REQUEST_RESPONSE_UNIQUE).
	StreamSignals(ctx context.Context, in *StreamSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSignalsResponse], error)
	// ValidateConfig dry-runs a candidate env-var map, matching
	// POST /v1/config/validate. Does not mutate the running server.
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	// ExportFederation returns anonymized pattern statistics, matching
	// GET /v1/federation/export. Returns Unimplemented unless
	// CHRONOS_FEDERATION_ENABLED=true.
	ExportFederation(ctx context.Context, in *ExportFederationRequest, opts ...grpc.CallOption) (*FederationExport, error)
}

type chronosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChronosServiceClient(cc grpc.ClientConnInterface) ChronosServiceClient {
	return &chronosServiceClient{cc}
}

func (c *chronosServiceClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, ChronosService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchResponse)
	err := c.cc.Invoke(ctx, ChronosService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) ListSignals(ctx context.Context, in *ListSignalsRequest, opts ...grpc.CallOption) (*ListSignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSignalsResponse)
	err := c.cc.Invoke(ctx, ChronosService_ListSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) GetSignal(ctx context.Context, in *GetSignalRequest, opts ...grpc.CallOption) (*Signal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Signal)
	err := c.cc.Invoke(ctx, ChronosService_GetSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) StreamSignals(ctx context.Context, in *StreamSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSignalsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChronosService_ServiceDesc.Streams[0], ChronosService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSignalsRequest, StreamSignalsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChronosService_StreamSignalsClient = grpc.ServerStreamingClient[StreamSignalsResponse]

func (c *chronosServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, ChronosService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) ExportFederation(ctx context.Context, in *ExportFederationRequest, opts ...grpc.CallOption) (*FederationExport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FederationExport)
	err := c.cc.Invoke(ctx, ChronosService_ExportFederation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChronosServiceServer is the server API for ChronosService service.
// All implementations must embed UnimplementedChronosServiceServer
// for forward compatibility.
//
// ChronosService is the gRPC transport for the Chronos perception engine.
// It mirrors the HTTP REST surface: ingest observations and query signals.
// The service is signals-only: no Title, Summary, Suggestion, or dismissal.
type ChronosServiceServer interface {
	// Ingest persists a single EntityState observation. Detection is not
	// triggered automatically; the scheduler or compute pipeline handles
	// detection separately. Unary — batch ingest is IngestBatch.
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	// IngestBatch persists many observations in one RPC. Validation is
	// all-or-nothing, matching POST /v1/ingest/batch.
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error)
	// ListSignals returns signals matching the provided filter.
	ListSignals(context.Context, *ListSignalsRequest) (*ListSignalsResponse, error)
	// GetSignal returns a single signal by ID.
	GetSignal(context.Context, *GetSignalRequest) (*Signal, error)
	// StreamSignals is the gRPC equivalent of GET /v1/signals/stream.
	// Requires the in-process detection scheduler. Returns Unimplemented
	// when streaming is not attached. Each frame is a StreamSignalsResponse
	// so the stream type is unique from GetSignal's Signal return
	// (RPC_REQUEST_RESPONSE_UNIQUE).
	StreamSignals(*StreamSignalsRequest, grpc.ServerStreamingServer[StreamSignalsResponse]) error
	// ValidateConfig dry-runs a candidate env-var map, matching
	// POST /v1/config/validate. Does not mutate the running server.
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	// ExportFederation returns anonymized pattern statistics, matching
	// GET /v1/federation/export. Returns Unimplemented unless
	// CHRONOS_FEDERATION_ENABLED=true.
	ExportFederation(context.Context, *ExportFederationRequest) (*FederationExport, error)
	mustEmbedUnimplementedChronosServiceServer()
}

// UnimplementedChronosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChronosServiceServer struct{}

func (UnimplementedChronosServiceServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedChronosServiceServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedChronosServiceServer) ListSignals(context.Context, *ListSignalsRequest) (*ListSignalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSignals not implemented")
}
func (UnimplementedChronosServiceServer) GetSignal(context.Context, *GetSignalRequest) (*Signal, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignal not implemented")
}
func (UnimplementedChronosServiceServer) StreamSignals(*StreamSignalsRequest, grpc.ServerStreamingServer[StreamSignalsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedChronosServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedChronosServiceServer) ExportFederation(context.Context, *ExportFederationRequest) (*FederationExport, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportFederation not implemented")
}
func (UnimplementedChronosServiceServer) mustEmbedUnimplementedChronosServiceServer() {}
func (UnimplementedChronosServiceServer) testEmbeddedByValue()                        {}

// UnsafeChronosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronosServiceServer will
// result in compilation errors.
type UnsafeChronosServiceServer interface {
	mustEmbedUnimplementedChronosServiceServer()
}

func RegisterChronosServiceServer(s grpc.ServiceRegistrar, srv ChronosServiceServer) {
	// If the following call panics, it indicates UnimplementedChronosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChronosService_ServiceDesc, srv)
}

func _ChronosService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_ListSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).ListSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_ListSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).ListSignals(ctx, req.(*ListSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_GetSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).GetSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_GetSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).GetSignal(ctx, req.(*GetSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSignalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChronosServiceServer).StreamSignals(m, &grpc.GenericServerStream[StreamSignalsRequest, StreamSignalsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChronosService_StreamSignalsServer = grpc.ServerStreamingServer[StreamSignalsResponse]

func _ChronosService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_ExportFederation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportFederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).ExportFederation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_ExportFederation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).ExportFederation(ctx, req.(*ExportFederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChronosService_ServiceDesc is the grpc.ServiceDesc for ChronosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronos.v1.ChronosService",
	HandlerType: (*ChronosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _ChronosService_Ingest_Handler,
		},
		{
			MethodName: "IngestBatch",
			Handler:    _ChronosService_IngestBatch_Handler,
		},
		{
			MethodName: "ListSignals",
			Handler:    _ChronosService_ListSignals_Handler,
		},
		{
			MethodName: "GetSignal",
			Handler:    _ChronosService_GetSignal_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _ChronosService_ValidateConfig_Handler,
		},
		{
			MethodName: "ExportFederation",
			Handler:    _ChronosService_ExportFederation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _ChronosService_StreamSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/chronos/v1/chronos.proto",
}
